### PR TITLE
Small refactoring

### PR DESCRIPTION
**Pull request by tatat**
This PR does

- Update package-lock.json
- Normalize indentation
- Access DOM elements using $refs
- Fix an error in tsconfig.json

I believe this PR could make the code a little more maintainable.

### CODE REVIEW

**Comment by tatat** [comment]
oh sorry, it seems to be broken...

**Comment by tatat** [comment]
It now seems to be working fine. I didn't do anything though

**Comment by monoai** [comment]
I don't see any problems on my side, though I will double-check the code on my local env first before seeing the merge.

**Comment by tatat** [comment]
Ah... I figured it out. tapping any checkbox causes some weird action.
it's not related to this PR.

**Comment by monoai** [comment]
I don't really see any issues, this looks like a good update.

As for the checkboxes, I don't see any issues considering it disables input on the checkboxes unless it's active, though if a user disables their checkbox manually it still shouldn't cause any problems since it would still work normally. (Tested on 3 browsers)
Though this leaves up either changing how the boxes will be shown as active in the future or leaving it as-is.

Thank you for the re-factoring! I haven't seen any problems so far, it seems to be working normally.

**Comment by tatat** [comment]
It makes sense!
I think iOS's hover behavior confused me.  (I tested on my iPhone)
Thank you for your reviewing and merging!

**Comment by monoai** [comment]
No problem! I also test on my iPhone so I make sure it works on mobile as well.

**Pull request merged**
